name: UI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.7.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: |
            core/package-lock.json
            ui/package-lock.json
      - name: Install core dependencies
        run: npm ci --prefix core
      - name: Build core package
        run: npm run build --prefix core
      - name: Install frontend dependencies
        run: npm ci --prefix ui
      - name: Build frontend
        run: npm run build --prefix ui
